version: "3.9"

services:
  db:
    image: postgres:16.2-alpine3.19
    container_name: integration-db
    ports:
      - "25432:5432"
    environment:
      POSTGRES_USER: integration
      POSTGRES_PASSWORD: password
      POSTGRES_DB: integration

  minio:
    image: minio/minio:RELEASE.2024-02-13T15-35-11Z
    container_name: integration-minio
    environment:
      MINIO_ROOT_USER: integration
      MINIO_ROOT_PASSWORD: password
    command:
      server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001

  minio-setup:
    image: minio/mc
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: integration
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./scripts/create-bucket.sh:/create-bucket.sh
    entrypoint: "/bin/sh"
    command: "/create-bucket.sh"
    networks:
      - default
